#practical 8 (?)- MISSING VALUES
airquality
dim(airquality)
air<- airquality
air
class(air)
dim(air)
str(air)
summary(air)
head(air)
tail(air)
air[,7]=c(NA)
air
air[154,]=c(NA)
air
dim(air)
summary(air)
is.na(air)
any(is.na(air[]))
any(is.na(women[]))
air=air[,-7]
air
air=air[-154,]
air
dim(air)
sum(is.na(air))
sum(is.na(air$Ozone))
sum(is.na(air$Solar.R))
sum(is.na(air$Wind))
sum(is.na(air$Temp))
sum(is.na(air$Month))
sum(is.na(air$Day))
length(which(is.na(air)))
which(is.na(air$Ozone))
colSums(is.na(air))
clean_air=na.omit(air)
clean_air
dim(clean_air)
mean(clean_air$Ozone)
mean(air$Solar.R,na.rm=T)
mean(clean_air$Solar.R)
replace(air$Ozone,5,100)
air3<-air
a<-which(is.na(air))
replace(air2$Ozone,a[1:5],100)
 